services:
  app:
    image: alswl/excalidraw:v0.17.3-fork-b1
    restart: unless-stopped
    environment:
      - VITE_APP_BACKEND_V2_GET_URL=http://${STORAGE_BACKEND_HOST}:${STORAGE_BACKEND_PORT}/api/v2/scenes/
      - VITE_APP_BACKEND_V2_POST_URL=http://${STORAGE_BACKEND_HOST}:${STORAGE_BACKEND_PORT}/api/v2/scenes/
      - VITE_APP_WS_SERVER_URL=http://${ROOM_HOST}:${ROOM_PORT}/
      - VITE_APP_FIREBASE_CONFIG={}
      - VITE_APP_HTTP_STORAGE_BACKEND_URL=http://${STORAGE_BACKEND_HOST}:${STORAGE_BACKEND_PORT}/api/v2
      - VITE_APP_STORAGE_BACKEND=http
      - VITE_APP_DISABLE_TRACKING=true
      - PUBLIC_URL=http://${APP_HOST}:${APP_PORT}
    ports:
      - "${APP_PORT}:80"
    networks:
      - draw-internal

  storage:
    image: alswl/excalidraw-storage-backend:v2023.11.11
    restart: unless-stopped
    environment:
      - STORAGE_URI=mongodb://${DB_USER}:${DB_PASS}@mongodb:27017
    ports:
      - "${STORAGE_BACKEND_PORT}:8080"
    networks:
      - draw-internal

  room:
    image: excalidraw/excalidraw-room:sha-49bf529
    restart: unless-stopped
    ports:
      - "${ROOM_PORT}:80"
    networks:
      - draw-internal

  mongodb:
    image: mongo:7.0.5-jammy
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ${DB_VOLUME_PATH}:/data/db
    networks:
      - draw-internal

  mongoexpress:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${DB_USER}:${DB_PASS}@mongodb:27017
      - ME_CONFIG_BASICAUTH=true
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASS}
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - "${MONGOEXPRESS_PORT}:8081"
    networks:
      - draw-internal

networks:
  draw-internal:
    name: draw-internal
    external: false
